AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront distribution for 2ndtolworth.org.uk

Parameters:
  DomainName:
    Type: String
    Default: 2ndtolworth.org.uk
  CertificateArn:
    Type: String
    Description: ACM certificate ARN in us-east-1 for the public Scouts hostname.
  OriginDomainName:
    Type: String
    Default: scouts-2ndtolworth-prod-553490163883.s3-website.eu-west-2.amazonaws.com

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref DomainName
        Origins:
          - Id: scouts-2ndtolworth-prod-s3-origin
            DomainName: !Ref OriginDomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: scouts-2ndtolworth-prod-s3-origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        CacheBehaviors:
          - PathPattern: /agenda.json
            TargetOriginId: scouts-2ndtolworth-prod-s3-origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            CachePolicyId: f6072fdc-ae27-4d49-a206-4f2a80c82fbe
          - PathPattern: /runtime/*
            TargetOriginId: scouts-2ndtolworth-prod-s3-origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            CachePolicyId: f6072fdc-ae27-4d49-a206-4f2a80c82fbe
          - PathPattern: /events/*
            TargetOriginId: scouts-2ndtolworth-prod-s3-origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            CachePolicyId: f6072fdc-ae27-4d49-a206-4f2a80c82fbe
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Restrictions:
          GeoRestriction:
            RestrictionType: whitelist
            Locations:
              - GB
        HttpVersion: http2
        IPV6Enabled: true

Outputs:
  DistributionId:
    Value: !Ref CloudFrontDistribution
  DistributionDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
