AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront distribution for 2ndtolworth.org.uk

Parameters:
  DomainName:
    Type: String
    Default: 2ndtolworth.org.uk
  EnableAlias:
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
  CertificateArn:
    Type: String
    Description: ACM certificate ARN in us-east-1 for the public Scouts hostname.
  OriginDomainName:
    Type: String
    Default: scouts-2ndtolworth-prod-553490163883.s3-website.eu-west-2.amazonaws.com

Conditions:
  UseAlias: !Equals [!Ref EnableAlias, "true"]

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases: !If
          - UseAlias
          - [!Ref DomainName]
          - !Ref AWS::NoValue
        Origins:
          - Id: scouts-2ndtolworth-prod-s3-origin
            DomainName: !Ref OriginDomainName
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          TargetOriginId: scouts-2ndtolworth-prod-s3-origin
          ViewerProtocolPolicy: redirect-to-https
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
        CacheBehaviors:
          - PathPattern: /agenda.json
            TargetOriginId: scouts-2ndtolworth-prod-s3-origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          - PathPattern: /runtime/*
            TargetOriginId: scouts-2ndtolworth-prod-s3-origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          - PathPattern: /events/*
            TargetOriginId: scouts-2ndtolworth-prod-s3-origin
            ViewerProtocolPolicy: redirect-to-https
            Compress: true
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Restrictions:
          GeoRestriction:
            RestrictionType: whitelist
            Locations:
              - GB
        HttpVersion: http2
        IPV6Enabled: true

Outputs:
  DistributionId:
    Value: !Ref CloudFrontDistribution
  DistributionDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
