import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

function read(relativePath) {
  return readFileSync(new URL(`../${relativePath}`, import.meta.url), 'utf8');
}

const scoutsSource = read('lambdas/scouts/function/scouts-service.mjs');
const workerSource = read('lambdas/sqs2scouts/function/image-provider-worker.mjs');
const workerCoreSource = read('lambdas/sqs2scouts/function/full-enrich-core.mjs');
const scoutsTemplate = read('lambdas/cloudformation/templates/scouts.yaml');
const workerTemplate = read('lambdas/cloudformation/templates/sqs2scouts.yaml');
const scoutsDeploy = read('lambdas/scouts/deploy.sh');
const retryDocs = read('GEMINI-ENRICHMENT-RETRY.md');

function sliceFunction(source, startMarker, endMarker) {
  const start = source.indexOf(startMarker);
  assert.notEqual(start, -1, `missing ${startMarker}`);
  const end = source.indexOf(endMarker, start + startMarker.length);
  assert.notEqual(end, -1, `missing ${endMarker}`);
  return source.slice(start, end);
}

test('scheduled enrichment checks per-stage state before both new and retry queue publication', () => {
  const eligibilityCalls = scoutsSource.match(/await checkEnrichmentEligibility\(/g) || [];
  assert.ok(eligibilityCalls.length >= 2, 'expected eligibility checks on new and stale/retry paths');
  assert.match(scoutsSource, /skipReason:\s*eligibility\.reason/);
  assert.match(scoutsSource, /state_store_unavailable/);
});

test('scheduled enrichment relies on per-stage state rather than a global daily request circuit', () => {
  assert.doesNotMatch(scoutsSource, /GEMINI_DAILY_REQUEST_LIMIT|isGeminiCircuitOpen|budget_circuit_/);
  assert.match(scoutsSource, /getEnrichmentState\(hex, stage\)/);
  assert.match(scoutsSource, /evaluateEnrichmentEligibility\(state, new Date\(\), generationId\)/);
});

test('CloudFormation provisions retry state, safe parameters, least-required DynamoDB actions and alarms', () => {
  for (const parameter of [
    'GeminiEnrichmentStateTableName',
    'GeminiMaxAttemptsPerStage',
    'GeminiRetryDelayAttempt2Seconds',
    'GeminiRetryDelayAttempt3Seconds',
    'GeminiInProgressLeaseSeconds',
  ]) {
    assert.match(workerTemplate, new RegExp(parameter));
  }
  assert.match(workerTemplate, /AttributeName:\s*hex/);
  assert.match(workerTemplate, /AttributeName:\s*stage/);
  assert.match(workerTemplate, /dynamodb:GetItem/);
  assert.match(workerTemplate, /dynamodb:PutItem/);
  assert.match(workerTemplate, /dynamodb:UpdateItem/);
  assert.match(workerTemplate, /GeminiEnrichmentQuarantineAlarm/);
  assert.match(workerTemplate, /GeminiEnrichmentRetryBurstAlarm/);
  assert.match(scoutsTemplate, /GEMINI_ENRICHMENT_STATE_TABLE_NAME/);
  assert.match(scoutsTemplate, /GeminiUsageTableName:\s*[\s\S]*?Default:\s*scouts-gemini-usage/);
  assert.doesNotMatch(scoutsTemplate, /GEMINI_DAILY_REQUEST_LIMIT|GeminiDailyRequestLimit/);
});

test('Scouts deployment reuses the existing API-key parameter when no replacement secret is supplied', () => {
  assert.match(scoutsDeploy, /require_existing_secure_parameter\(\)/);
  assert.match(scoutsDeploy, /if \[ -z "\$\{REQUIRED_API_KEY\}" \]; then require_existing_secure_parameter "\$\{REQUIRED_API_KEY_PARAMETER\}"; fi/);
  assert.match(scoutsDeploy, /if \[ -n "\$\{REQUIRED_API_KEY\}" \]; then put_standard_secure_parameter/);
});

test('image provider calls are owned by atomic stage reservation before any external call', () => {
  const cloudflareFlow = sliceFunction(workerSource, 'async function processCloudflareImage', 'async function sendTaskSuccess');
  const cloudflareReserve = cloudflareFlow.search(/await\s+reserveEnrichmentAttempt\s*\(/);
  const cloudflareCall = cloudflareFlow.search(/await\s+generateCloudflareImageAsset\s*\(/);
  assert.ok(cloudflareReserve >= 0 && cloudflareCall > cloudflareReserve, 'Cloudflare stage reservation must precede the external call');

  const geminiFlow = sliceFunction(workerCoreSource, 'async function processImageProvider', 'async function resultAfterProcessor');
  const geminiReserve = geminiFlow.search(/await\s+reserveEnrichmentAttempt\s*\(/);
  const geminiCall = geminiFlow.search(/await\s+callGemini\s*\(\s*prompt\s*\)/);
  assert.ok(geminiReserve >= 0 && geminiCall > geminiReserve, 'Gemini fallback stage reservation must precede the external call');
});

test('provider success is cached before event persistence so persistence retries do not regenerate', () => {
  const cloudflareFlow = sliceFunction(workerSource, 'async function processCloudflareImage', 'async function sendTaskSuccess');
  const cloudflareCache = cloudflareFlow.indexOf('await markGeminiSucceeded');
  const cloudflarePersist = cloudflareFlow.indexOf('await persistCachedImage', cloudflareCache);
  assert.ok(cloudflareCache >= 0 && cloudflarePersist > cloudflareCache, 'Cloudflare generated bytes must be cached before S3/event persistence');
  assert.match(cloudflareFlow, /loadReusableGeneration/);
  assert.match(cloudflareFlow, /persistence_pending/);

  const geminiFlow = sliceFunction(workerCoreSource, 'async function processImageProvider', 'async function resultAfterProcessor');
  const geminiCache = geminiFlow.indexOf('await markGeminiSucceeded');
  const geminiPersist = geminiFlow.indexOf('await persistGeneratedImage', geminiCache);
  assert.ok(geminiCache >= 0 && geminiPersist > geminiCache, 'Gemini rollback result must be cached before event persistence');
  assert.match(geminiFlow, /loadReusableGeneration/);
});

test('Slack escalation is warning-on-second-attempt and quarantine-once', () => {
  const notification = sliceFunction(workerSource, 'async function notifyTransition', 'async function readUsage');
  assert.match(notification, /state\.state === 'retry_wait' && attemptCount === 2/);
  assert.match(notification, /state\.state === 'manual_review'/);
  assert.match(notification, /claimEnrichmentEscalation/);
});

test('manual recovery is documented and requires an explicit HEX + stage reset', () => {
  assert.match(retryDocs, /resetEnrichmentState/);
  assert.match(retryDocs, /HEX_VALUE STAGE/);
  assert.match(retryDocs, /manual_review/);
});
