name = "scouts-admin-proxy"
main = "worker.js"
compatibility_date = "2026-03-03"

routes = [
  { pattern = "2ndtolworth.org.uk/admin-api/*", zone_name = "2ndtolworth.org.uk" }
]

[vars]
# Set to "true" to require a Cloudflare Access JWT on incoming requests.
REQUIRE_CF_ACCESS = "true"
SCOUTS2SQS_URL = "https://makwmjq3oycgcrrorhn7tndsaa0ujnyh.lambda-url.eu-west-2.on.aws/"
SCOUTS_REFRESH_URL = "https://h6ibdinq6dnu2zjekd4aqgkp2a0brmrh.lambda-url.eu-west-2.on.aws/"
